CREATE TABLE livro(
id_livro INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR(254),
autor VARCHAR(254),
ano_publicado INTEGER
)

INSERT INTO LIVRO(nome,autor,ano_publicado)
VALUES ('Quarto de Despejo','Carolina Maria de Jesus', '2000');
INSERT INTO LIVRO(nome,autor,ano_publicado)
VALUES ('Todas as suas imperfeições','Collen Hoover', '2023');
INSERT INTO LIVRO(nome,autor,ano_publicado)
VALUES ('Turma da Mônica','Mauricio de Souza', '2019');

SELECT l.NOME, l.AUTOR, l.ANO_PUBLICADO
FROM LIVRO l 

SELECT * FROM livro

SELECT nome
  FROM livro
 WHERE nome = 'Quarto de Despejo'

SELECT 1 FROM livro WHERE nome = ?	

SELECT * FROM livro